version: "3"
services:
  ezq42example:
    build: .
    network_mode: host
    environment:
      - "EZQ42_EMAIL=${EZQ42_EMAIL}"
      - "EZQ42_URL=${EZQ42_URL}"
      - "NEXT_PUBLIC_VERCEL_URL=${NEXT_PUBLIC_VERCEL_URL}"
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
